package bo.net.tigo.model;

/**
 * Created by aralco on 12/7/14.
 */
public enum Action {
    AUTENTICACION, CREAR_PROGRAMACION, EDITAR_PROGRAMACION, ELIMINAR_PROGRAMACION,
    CREAR_TAREA, EDITAR_TAREA, ELIMINAR_TAREA, CREAR_CIUDAD, EDITAR_CIUDAD,
    CREAR_CONTACTO, EDITAR_CONTACTO, CREAR_USUARIO, EDITAR_USUARIO
}
