INSERT INTO "IMPORTLUCKY"."ILN_USER"
   (	"ILN_USER_ID",
	"ILN_USER_NAME",
	"ILN_USER_EMAIL1",
	"ILN_USER_EMAIL2",
	"ILN_USER_PHONE1",
	"ILN_USER_PHONE2",
	"ILN_USER_PHONE3",
	"ILN_USER_DESCRIPTION",
	"ILN_USER_CREATED_DATE",
	"ILN_USER_ENABLED",
	"ILN_USER_USERNAME",
	"ILN_USER_ROLE") VALUES (
	ILN_USER_SEQ_ID.NEXTVAL,
	'Usuario administrador Admin',
	'admin@email.com',
	'admin@email.com',
	'77960969',
	'000000',
	'000000',
	'Usuario administrador admin',
	sysdate,
	1,
	'admin',
	'ROLE_ADMIN')
